#Setup
title: "CU Codes Open"
description: "Cornell University's open science study group."
language: en

titleBackground: assets/lee-campbell-86958.jpg
headlineSmall: ""
headlineMain: "Let's work <br> together"

# Setup Google Calendar
# Usage:
# 1. create a new google account; set the calendar to 'public' (see https://support.google.com/calendar/answer/37083?hl=en on how to do this)
# 2. change 'USER' in the example urls below to the username of the google account you made for your calendar
# 3. set calendar_on: True.

calendar_on: False
calendar_embed_url: "https://www.google.com/calendar/embed?src=USER@gmail.com"
calendar_ical_url: "https://www.google.com/calendar/ical/USER@gmail.com/public/basic.ics"

# ===============================
# Categories for sorting lessons.
# ===============================

languages:
  - git

levels:
  - intro
  - intermediate
  - advanced


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2f85d0
  secondary: 256ba6
  secondary-dark: 256ba6

# Build settings
markdown: kramdown
permalink: pretty
future: true
